/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author julia
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblInfo = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblNick = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListContactos = new javax.swing.JList();
        btnAddContacto = new javax.swing.JButton();
        lblActions = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        btnComentar = new javax.swing.JButton();
        btnSubirFoto = new javax.swing.JButton();
        lblGrupo = new javax.swing.JPanel();
        btnCrearGrupo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListGrupos = new javax.swing.JList<>();
        lblNombre1 = new javax.swing.JLabel();
        btnMostrarInfo = new javax.swing.JButton();
        txtNombreGrupo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblNombre3 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();
        jComboBoxMostrarGrupo = new javax.swing.JComboBox<>();
        lblNombre5 = new javax.swing.JLabel();
        jComboBoxMisGrupos = new javax.swing.JComboBox<>();
        btnAddIntegrante = new javax.swing.JButton();
        lblNombre6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListIntegrantes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblInfo.setToolTipText("");
        lblInfo.setName(""); // NOI18N

        lblNombre.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("nombre");

        lblNick.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        lblNick.setForeground(new java.awt.Color(0, 0, 0));
        lblNick.setText("nick");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CONTACTOS");

        jListContactos.setBackground(new java.awt.Color(51, 51, 51));
        jListContactos.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jListContactos);

        btnAddContacto.setText("AÑADIR CONTACTO");

        javax.swing.GroupLayout lblInfoLayout = new javax.swing.GroupLayout(lblInfo);
        lblInfo.setLayout(lblInfoLayout);
        lblInfoLayout.setHorizontalGroup(
            lblInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNick)
                    .addComponent(lblNombre)
                    .addGroup(lblInfoLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(lblInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddContacto)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        lblInfoLayout.setVerticalGroup(
            lblInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddContacto)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel1.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));
        lblInfo.getAccessibleContext().setAccessibleName("");

        lblActions.setBackground(new java.awt.Color(153, 153, 153));

        txtComentarios.setEditable(false);
        txtComentarios.setBackground(new java.awt.Color(51, 51, 51));
        txtComentarios.setColumns(20);
        txtComentarios.setForeground(new java.awt.Color(255, 255, 255));
        txtComentarios.setLineWrap(true);
        txtComentarios.setRows(5);
        jScrollPane2.setViewportView(txtComentarios);

        txtComentario.setBackground(new java.awt.Color(51, 51, 51));
        txtComentario.setColumns(20);
        txtComentario.setForeground(new java.awt.Color(255, 255, 255));
        txtComentario.setLineWrap(true);
        txtComentario.setRows(5);
        jScrollPane3.setViewportView(txtComentario);

        btnComentar.setText("COMENTAR");

        btnSubirFoto.setText("SUBIR FOTO");

        javax.swing.GroupLayout lblActionsLayout = new javax.swing.GroupLayout(lblActions);
        lblActions.setLayout(lblActionsLayout);
        lblActionsLayout.setHorizontalGroup(
            lblActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblActionsLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(lblActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblActionsLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(lblActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubirFoto)
                            .addComponent(btnComentar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        lblActionsLayout.setVerticalGroup(
            lblActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblActionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lblActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lblActionsLayout.createSequentialGroup()
                        .addComponent(btnComentar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubirFoto)
                        .addGap(17, 17, 17)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(lblActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 480, 500));

        lblGrupo.setBackground(new java.awt.Color(255, 255, 255));

        btnCrearGrupo.setText("CREAR GRUPO");

        jListGrupos.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane4.setViewportView(jListGrupos);

        lblNombre1.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre1.setText("GRUPOS");

        btnMostrarInfo.setText("MOSTRAR INFO");

        txtNombreGrupo.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        txtNombreGrupo.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreGrupo.setText("NOMBRE");

        txtDescripcion.setBackground(new java.awt.Color(51, 51, 51));
        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        jScrollPane5.setViewportView(txtDescripcion);

        lblNombre3.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblNombre3.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre3.setText("DESCRIPCION");

        lblNombre4.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblNombre4.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre4.setText("GRUPO:");

        lblNombre5.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblNombre5.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre5.setText("MIS GRUPOS");

        btnAddIntegrante.setText("NUEVO INTEGRANTE");
        btnAddIntegrante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIntegranteActionPerformed(evt);
            }
        });

        lblNombre6.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        lblNombre6.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre6.setText("INTEGRANTES");

        jListIntegrantes.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane6.setViewportView(jListIntegrantes);

        javax.swing.GroupLayout lblGrupoLayout = new javax.swing.GroupLayout(lblGrupo);
        lblGrupo.setLayout(lblGrupoLayout);
        lblGrupoLayout.setHorizontalGroup(
            lblGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblGrupoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(lblGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblGrupoLayout.createSequentialGroup()
                        .addGroup(lblGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblGrupoLayout.createSequentialGroup()
                                .addComponent(lblNombre4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxMostrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNombre1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarInfo))
                    .addComponent(btnCrearGrupo)
                    .addComponent(txtNombreGrupo)
                    .addGroup(lblGrupoLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lblGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre5)
                            .addComponent(jComboBoxMisGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddIntegrante, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(lblGrupoLayout.createSequentialGroup()
                        .addComponent(lblNombre3)
                        .addGap(66, 66, 66)
                        .addComponent(lblNombre6))
                    .addGroup(lblGrupoLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblGrupoLayout.setVerticalGroup(
            lblGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrearGrupo)
                .addGap(24, 24, 24)
                .addGroup(lblGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre1)
                    .addComponent(lblNombre5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblGrupoLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(lblGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre4)
                            .addComponent(jComboBoxMostrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(txtNombreGrupo))
                    .addGroup(lblGrupoLayout.createSequentialGroup()
                        .addComponent(jComboBoxMisGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddIntegrante)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(lblGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre3)
                    .addComponent(lblNombre6))
                .addGap(1, 1, 1)
                .addGroup(lblGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159))
        );

        jPanel1.add(lblGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 310, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1026, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddIntegranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIntegranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddIntegranteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddContacto;
    public javax.swing.JButton btnAddIntegrante;
    public javax.swing.JButton btnComentar;
    public javax.swing.JButton btnCrearGrupo;
    public javax.swing.JButton btnMostrarInfo;
    public javax.swing.JButton btnSubirFoto;
    public javax.swing.JComboBox<String> jComboBoxMisGrupos;
    public javax.swing.JComboBox<String> jComboBoxMostrarGrupo;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JList jListContactos;
    public javax.swing.JList<String> jListGrupos;
    public javax.swing.JList<String> jListIntegrantes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel lblActions;
    private javax.swing.JPanel lblGrupo;
    private javax.swing.JPanel lblInfo;
    public javax.swing.JLabel lblNick;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblNombre1;
    public javax.swing.JLabel lblNombre3;
    public javax.swing.JLabel lblNombre4;
    public javax.swing.JLabel lblNombre5;
    public javax.swing.JLabel lblNombre6;
    public javax.swing.JTextArea txtComentario;
    public javax.swing.JTextArea txtComentarios;
    public javax.swing.JTextArea txtDescripcion;
    public javax.swing.JLabel txtNombreGrupo;
    // End of variables declaration//GEN-END:variables
}
